Jc/mask card
franckdarren/mbulu pull request #13
Opened 2024-07-29 20:21 UTC by jeanclaudesperandezi

ajout code pour change le texte en fonction de  du choix de l'option

2024-07-29 21:36 UTC, franckdarren commented on app/dictionnaire/page.js
> +                        Dictionnaire {selectedOption.split("-")[0].trim()}
Ca sa sert à quoi? Il faut m'expliquer
Arrêtes de copier du code sans comprendre.

2024-07-29 21:37 UTC, franckdarren commented on app/dictionnaire/page.js
> +                <option value="FrancaisPunu">Français - Punu</option>
C'est par ordre alphabétique. Fang, Myene, Punu. Corriges

2024-07-29 21:38 UTC, franckdarren requested changes
Il faut corriger ton code.

2024-07-29 21:46 UTC, jeanclaudesperandezi commented on app/dictionnaire/page.js
> +                <option value="FrancaisPunu">Français - Punu</option>
d'accord

2024-07-30 12:31 UTC, mandochrist13 commented on app/dictionnaire/page.js
> +                <option value="FrancaisPunu">Français - Punu</option>
Tout les jours on te parle des mêmes choses

2024-07-30 12:32 UTC, mandochrist13 commented on app/dictionnaire/page.js
> +                        Dictionnaire {selectedOption.split("-")[0].trim()}
il ne va pas te dire. là il active son mode lée charlie

2024-08-05 15:10 UTC, closed without merging