Ajout du contenu d'un cours
franckdarren/mbulu pull request #15
Opened 2024-08-04 18:25 UTC by mandochrist13

je viens de faire la page qui servira de model pour le contenu de chaque cours. je me suis assurer de sa responsivité, néamoins il reste à mettre en paramètre les différent élément qui viendront de la base de données, relativement à chaque courq et à chaque langue.

2024-08-06 06:07 UTC, mandochrist13 reviewed
je viens de faire les modifs du build

2024-08-07 23:45 UTC, mandochrist13 reviewed
je ne suis pas très inspiré malheureusement. avançons ainsi dab

2024-08-08 23:27 UTC, mandochrist13 reviewed
j'ai ajouté les espaces et changer l'image

2024-08-10 13:20 UTC, franckdarren commented on app/dictionnaire/dictionnaire.jsx
>  export function Dictionnaire({titre, text, other}){
Change le nom du composant et appele le différement : Définition

2024-08-10 13:21 UTC, franckdarren commented on app/dictionnaire/dictionnaire.jsx
> +        <div className="mx-[100px] my-[25px] bg-amber-50 border rounded-xl px-6 animate-levitate py-2">
Pourquoi ca flotte?? Trop d'annimation tue le design. Laisse le simple et épuré. Tu as déja un gif qui bouge, pourquoi faire aussi celui la bouger???
Enlève ca

2024-08-10 13:26 UTC, franckdarren commented on app/dictionnaire/page.js
> +      <Footer />
je tai demandé de faire tenir la page sur l'écran. Tu as le choix de reduire les éléments du haut. Toi tu viens me mofier la hauteur du footer.
Ce n'est pas bon. Corriges ca. Les tailles de textes de toute la page sont trop grandes. Harmonise ca. Tu peux faire un benchmark sur internet et avec lextension font Ninja tu peu retrouver les tailles des polices.

2024-08-10 13:28 UTC, franckdarren commented on app/_components/WordDetail.jsx
> +// components/ImageDisplay.js
Ca sert a quoi?

2024-08-10 13:28 UTC, franckdarren commented on app/_components/WordList.jsx
> +// components/WordList.js
Ca sert a quoi? je tai demandé de mettre des valeurs en dure. Pas de copier ChatGPT

2024-08-10 13:32 UTC, franckdarren commented on app/cours/[slug]/[cours]/page.js
> +"use client";
La page ne s'affiche pas. Probablement car tu est allé copier des choses sans comprendre. Fais ce que je tai dis, intègre le design et met les valeurs en dure. C'EST TOUT

2024-08-10 13:34 UTC, franckdarren reviewed
> je viens de faire la page qui servira de model pour le contenu de chaque cours. je me suis assurer de sa responsivité, néamoins il reste à mettre en paramètre les différent élément qui viendront de la base de données, relativement à chaque courq et à chaque langue.

2024-08-10 13:36 UTC, franckdarren reviewed
Je ne tai jamais demandé de passer des paramètres. Je tai dis de tout mettre en dure. Le reste je vais m'en charger. Donc limite toi a ce que je tai dis

2024-08-10 13:39 UTC, franckdarren requested changes
Je t'ai demandé de gérer les espacements des sections sur la page d'acceuil, tu n'as pas fais. Je t'ai demandé d'intégrer la page de cours dans le dashboard, tu na pas fais. Mais tu vas crée des composants avec des datas et au finish la page ne fonctionne pas. Ce n'est vraiment pas bon. La ca fait une semaine et tu n'as pas fais avancé le projet.

2024-08-10 13:39 UTC, closed without merging