fix bug liste mots d'un cours
franckdarren/mbulu pull request #18
Opened 2024-08-12 10:25 UTC by mandochrist13

j'ai réglé le problème de la balise image, du coup je préfère laisser les choses en dynamique pour te montrer comment la page et les boutons doivent se comporter. tu pourra toujours modifier pour ce qui est de la page d'affichage d'un cours. de même, la page dictionnaire a été gérer, j'ai enlever la lévitation, régler la barre de navigation et le footer.

2024-08-12 10:56 UTC, franckdarren requested changes
Effaces tout ce que tu as mis comme useState, useEffect , map et autres. Mets moi les valeurs en dures simplement.

2024-08-12 11:11 UTC, mandochrist13 reviewed
fig bug image

2024-08-12 11:37 UTC, mandochrist13 reviewed
j'ai effacé

2024-08-12 11:38 UTC, mandochrist13 reviewed
le problème était la balise link

2024-08-13 05:43 UTC, mandochrist13 reviewed
j'ai effectuer des corrections , je sais pas si il y'a trop d'espace

2024-08-13 08:09 UTC, mandochrist13 reviewed
j'ai fais des ajustements ça et la concernant la page cours. je ne l'ai pas encore déporter vers la partie admin

2024-08-13 15:38 UTC, franckdarren approved these changes

2024-08-13 15:38 UTC, merged