responsive admin
franckdarren/mbulu pull request #20
Opened 2024-09-06 05:22 UTC by mandochrist13

j'ai gérer le responsive de toutes les pages côté admin et de même j'ai trouvé le problème de la cassure lié à la déconnection.

2024-09-06 19:27 UTC, franckdarren commented on app/_components/AdminTitre.jsx
> +        <h2 className="font-bold text-3xl text-center md:text-left pt-5 md:pl-6 mb-6">
Laisses comme c'était. 
font-bold text-3xl pt-5 mb-6

2024-09-06 19:29 UTC, franckdarren commented on app/_components/Aside.jsx
> +        <aside className="aside is-placed-left h-full lg:fixed is-expanded">
Pourquoi? je comprend pas

2024-09-06 19:33 UTC, franckdarren commented on app/admin/layout.js
> +    <div className="mt-5">
Remets ce qui était avant : mt-5 mx-5.
Car quand tu enlèves mx-5, les éléments sont colés sur les bords de l'écran et du coup ce n'est pas sexy.

2024-09-06 19:34 UTC, franckdarren commented on app/page.js
> +    <main className="relative z-0">
expliques moi ce que fais ce code stp

2024-09-06 19:35 UTC, franckdarren requested changes
Je t'ai laissé des commentaires!!!!!

2024-09-06 22:01 UTC, mandochrist13 commented on app/_components/Aside.jsx
> +        <aside className="aside is-placed-left h-full lg:fixed is-expanded">
pour ne plus que ca bouge. ca poussait le children au lieu de passer par dessus également

2024-09-06 22:02 UTC, mandochrist13 commented on app/_components/AdminTitre.jsx
> +        <h2 className="font-bold text-3xl text-center md:text-left pt-5 md:pl-6 mb-6">
ok

2024-09-06 22:02 UTC, mandochrist13 commented on app/admin/layout.js
> +    <div className="mt-5">
ok

2024-09-06 22:04 UTC, mandochrist13 commented on app/page.js
> +    <main className="relative z-0">
il permet de résoudre le problème de la cassure, pour que le vide créer par le navadmin et le aside ne se répercute pas sur la page d'accueil lorsqu'on se déconnecte

2024-09-06 22:37 UTC, mandochrist13 reviewed
modification apporté

2024-09-08 17:07 UTC, franckdarren approved these changes

2024-09-08 17:08 UTC, merged